DROP TABLE IF EXISTS "match" CASCADE;
DROP TABLE IF EXISTS "rating_current" CASCADE;
DROP TABLE IF EXISTS "rating_historical" CASCADE;
DROP TABLE IF EXISTS "tournament" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;

CREATE TABLE "user" ("id" UUID NOT NULL , "username" VARCHAR(255) NOT NULL UNIQUE, "type" VARCHAR(255) NOT NULL, "first_name" VARCHAR(255), "last_name" VARCHAR(255), "email" VARCHAR(255) NOT NULL, "password_hashed" VARCHAR(255) NOT NULL, PRIMARY KEY ("id"));
CREATE TABLE "tournament" ("id" UUID NOT NULL , "name" VARCHAR(255) NOT NULL, "start_at" TIMESTAMP WITH TIME ZONE NOT NULL, "end_at" TIMESTAMP WITH TIME ZONE NOT NULL, "processed" BOOLEAN NOT NULL, PRIMARY KEY ("id"));
CREATE TABLE "match" ("id" UUID NOT NULL , "date" DATE NOT NULL, "start_at" TIMESTAMP WITH TIME ZONE, "end_at" TIMESTAMP WITH TIME ZONE, "result" VARCHAR(255), "user1_id" UUID NOT NULL REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE CASCADE, "user2_id" UUID NOT NULL REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE CASCADE, "tournament_id" UUID NOT NULL REFERENCES "tournament" ("id") ON DELETE NO ACTION ON UPDATE CASCADE, PRIMARY KEY ("id"));
CREATE TABLE "rating_current" ("id" UUID NOT NULL , "value" DECIMAL NOT NULL, "user_id" UUID NOT NULL REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE CASCADE, "tournament_id" UUID NOT NULL REFERENCES "tournament" ("id") ON DELETE NO ACTION ON UPDATE CASCADE, UNIQUE ("user_id", "tournament_id"), PRIMARY KEY ("id"));
CREATE TABLE "rating_historical" ("id" UUID NOT NULL , "value" DECIMAL NOT NULL, "user_id" UUID NOT NULL REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE CASCADE, "tournament_id" UUID NOT NULL REFERENCES "tournament" ("id") ON DELETE NO ACTION ON UPDATE CASCADE, UNIQUE ("user_id", "tournament_id"), PRIMARY KEY ("id"));
